# 服务器配置
server:
  port: 20000

#spring配置
spring:
  #数据源配置
  datasource:
    url: jdbc:postgresql://192.168.134.132:5432/catguild
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

# 日志配置
logging:
  config: classpath:log/logback.xml
