# 服务器配置
server:
  port: 20000
  undertow:
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    buffer-size: 1024
    # 是否分配的直接内存
    direct-buffers: true
    threads:
      io: 4 # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
      worker: 20 # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载

#spring配置
spring:
  #数据源配置
  datasource:
    druid:
      # JDBC 配置
      url: jdbc:mysql://192.168.134.138:3306/catguild
      username: root
      password: 123456
      # 连接池配置
      # 监控配置
      initial-size: 1  # 初始化大小
      min-idle: 1  # 最小
      max-active: 10   # 最大
      max-wait: 6000 # 配置获取连接等待超时的时间
      time-between-eviction-runs-millis: 2000 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 600000 # 配置一个连接在池中最小生存的时间，单位是毫秒
      max-evictable-idle-time-millis: 900000 # 配置一个连接在池中最大生存的时间，单位是毫秒

      validation-query: select 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

      keep-alive: true
      phy-max-use-count: 500

      filters: stat  # 配置监控统计拦截的filters


# 日志配置
logging:
  config: classpath:log/logback.xml
