
spring:
  data:
    mongodb:
      host: 192.168.134.132
      port: 27017
      database: catguild_db
logging:
  config: classpath:log/logback.xml
#  level:
#    org.springframework.data: debug
#    cn.catguild: debug
server:
  port: 20000
