# 服务器配置
server:
  port: 20000
  undertow:
    # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    buffer-size: 1024
    # 是否分配的直接内存
    direct-buffers: true
    threads:
      io: 4 # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
      worker: 20 # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载

#spring配置
spring:
  #数据源配置
  datasource:
    # 自动执行sql
    schema:
      - classpath:sql/schema-mysql.sql
    sql-script-encoding: utf-8
    platform: mysql
    initialization-mode: always

    druid:
      # JDBC 配置
      # url: jdbc:mysql://192.168.134.138:3306/catguild?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8
      url: jdbc:p6spy:mysql://192.168.42.128:3306/catguild?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8
      username: root
      password: 123456
      driver-class-name: com.p6spy.engine.spy.P6SpyDriver
      # 连接池配置
      # 监控配置
      initial-size: 1  # 初始化大小
      min-idle: 1  # 最小
      max-active: 10   # 最大
      max-wait: 6000 # 配置获取连接等待超时的时间
      time-between-eviction-runs-millis: 2000 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 600000 # 配置一个连接在池中最小生存的时间，单位是毫秒
      max-evictable-idle-time-millis: 900000 # 配置一个连接在池中最大生存的时间，单位是毫秒

      validation-query: select 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

      keep-alive: true
      phy-max-use-count: 500

      filters: stat  # 配置监控统计拦截的filters

# mybatis-plus的配置
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: is_deleted  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: UNIX_TIMESTAMP() # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  # 配置通用枚举扫描
  typeEnumsPackage: cn.catguild.core.domain.enums # 支持统配符 * 或者 ; 分割


# 日志配置
logging:
  config: classpath:log/logback.xml
