spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: catguild_db
logging:
  config: classpath:log/logback.xml
#  level:
#    org.springframework.data: debug
#    cn.catguild: debug

